In [1]:
import os

In [2]:
os.path.isfile('/mnt/home/larend/kfx/data/2022-07-27-hpc-spikes.pkl')

True

In [3]:
import pandas as pd

In [7]:
blob = pd.read_pickle('/mnt/home/larend/kfx/data/2022-07-27-hpc-spikes.pkl')

In [10]:
len(blob)

3

In [11]:
blob[0]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [12]:
blob[0].shape

(565, 1800499)

In [18]:
import numpy as np

In [29]:
import pandas as pd

In [31]:
pd.DataFrame(blob[0]).value_counts()

KeyboardInterrupt: 

In [20]:
blob[1]

array([  61,  266,  549,  523,  535,  125,  334,  383,  283,  559,  236,
       1090,  552,  469,  288,  646,   62,  273, 1164,  877,  275,    0,
        384,  454,  731, 1194,   20,  550,  530,  177,   32, 1153,  339,
        702,  607,  626,  571,  476,   36,    9,   72,  112,   63,   74,
        123,  264,   27,  555,    1,  580,  325,  289,  546,  578,  596,
        367,  579,  183,  457,  427,  407,  563,  458,  576,  905,  411,
        395,  417,  642,  151,  240,   13,   29,  403,   94,  419,  617,
        693,  594,  734,  739,  397,  639,  650, 1006,  490,  885,  588,
        329,  532,  902,  482,  493,  524,  715,  953,  855,  391, 1127,
       1142,  859,  871, 1046,  832,  913,   15,  161,  562,   41,  380,
        170,  874,  712,  197,  466,  870, 1120,  602,  695,  613,  906,
        897,  187,  748,  733,  890,  645,  263,   11,  277,  290,  719,
        227,  366,  725,  400,  895,  249,  945,  190, 1068,  233,  697,
        483,  192,  669,  229,   69,  278,  279,  3

In [14]:
len(blob[1])

565

In [15]:
blob[2]

array([  2,   3,   3,   2,   1,   0,   5,   2,   2,   1,   5,   1,   5,
         3,   3,   3,   1,   6,   8,   7,   6,   7,   7,   5,   7,   9,
         7,   6,   6,   6,   4,   4,   4,  13,  11,  13,  10,   9,   9,
        16,  13,  16,  17,  17,  10,  10,  15,  10,  17,  10,  10,  14,
        14,  14,  14,  14,  13,  13,  12,  17,  20,  16,  18,  20,  20,
        18,  17,  21,  21,  17,  21,  15,  17,  17,  17,  21,  20,  18,
        22,  24,  24,  20,  23,  20,  24,  26,  19,  24,  29,  29,  29,
        28,  29,  28,  27,  29,  24,  29,  29,  29,  30,  30,  30,  29,
        30,  30,  31,  28,  28,  29,  29,  31,  31,  31,  31,  31,  31,
        29,  31,  31,  31,  34,  34,  35,  32,  32,  33,  33,  35,  34,
        37,  35,  35,  34,  34,  40,  36,  39,  38,  36,  37,  39,  42,
        42,  36,  44,  43,  44,  45,  46,  46,  46,  44,  48,  45,  46,
        48,  47,  50,  45,  46,  46,  46,  46,  46,  50,  48,  52,  52,
        52,  51,  51,  52,  53,  48,  43,  51,  52,  52,  55,  5